//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingRoomBot.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeetingRoomBot.Languages.BotMessages", typeof(BotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve booked  {roomid} on {startDateTime} for {duration} hours.
        /// </summary>
        internal static string Confirm_Booked {
            get {
                return ResourceManager.GetString("Confirm_Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but there is no room available that meets your criteria.
        /// </summary>
        internal static string Confirm_Unsuccessfully {
            get {
                return ResourceManager.GetString("Confirm_Unsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am Meeting Room bot, I am here to help you book meeting room efficiently.
        /// </summary>
        internal static string Help_Greeting {
            get {
                return ResourceManager.GetString("Help_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can say &quot;book a room tomorrow morning 9 AM for 2 people&quot;.
        /// </summary>
        internal static string Help_SyntaxHints_1 {
            get {
                return ResourceManager.GetString("Help_SyntaxHints_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or &quot;book A901 next monday at 10 AM for 1 hour&quot;.
        /// </summary>
        internal static string Help_SyntaxHints_2 {
            get {
                return ResourceManager.GetString("Help_SyntaxHints_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long would this meeting take ?.
        /// </summary>
        internal static string Hint_ProvideDuration {
            get {
                return ResourceManager.GetString("Hint_ProvideDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any preferred meeting room ? please spcify the meeting room Id, such as, A901.
        /// </summary>
        internal static string Hint_ProvideRoomId {
            get {
                return ResourceManager.GetString("Hint_ProvideRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many people would attend this meeting in-person ?.
        /// </summary>
        internal static string Hint_ProvideSize {
            get {
                return ResourceManager.GetString("Hint_ProvideSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which date would your meeting start ?.
        /// </summary>
        internal static string Hint_ProvideStartDate {
            get {
                return ResourceManager.GetString("Hint_ProvideStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would this meeting starts ? please specify date and time..
        /// </summary>
        internal static string Hint_ProvideStartDateTime {
            get {
                return ResourceManager.GetString("Hint_ProvideStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time is the meeting ?.
        /// </summary>
        internal static string Hint_ProvideStartTime {
            get {
                return ResourceManager.GetString("Hint_ProvideStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been cancelled.
        /// </summary>
        internal static string Hint_UserCancel {
            get {
                return ResourceManager.GetString("Hint_UserCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please repeat that again.
        /// </summary>
        internal static string Question_RepeatQuestion {
            get {
                return ResourceManager.GetString("Question_RepeatQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found these room for you.
        /// </summary>
        internal static string Question_SuggestedRooms {
            get {
                return ResourceManager.GetString("Question_SuggestedRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve tried too many times.
        /// </summary>
        internal static string Question_TooManyAttempts {
            get {
                return ResourceManager.GetString("Question_TooManyAttempts", resourceCulture);
            }
        }
    }
}
